name: Backend Test

on:
  push:
  pull_request:

jobs:
  lint:
      name: golangci-lint
      runs-on: ubuntu-latest
      steps:
        - name: Check out code into the Go module directory
          uses: actions/checkout@v3
        - name: golangci-lint
          uses: reviewdog/action-golangci-lint@v2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            golangci_lint_flags: "--timeout=5m --config=./.golangci.yml ./..."
            fail_on_error: true
            reporter: "github-pr-review"
  golang-test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: testing
        run: |
          go test ./... -coverprofile=coverage.out

      - name: create report
        uses: k1LoW/octocov-action@v0